export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_SUCCESSFUL_REGISTER = 'SET_SUCCESSFUL_REGISTER';
export const CLEAR_REGISTER = 'CLEAR_REGISTER';

export const CHANGE_SIDEBAR_VISIBILITY = 'CHANGE_SIDEBAR_VISIBILITY';